### ISSUE TITLE
[BUG] some skill don't work

### ISSUE THREAD

**Issue by omega6428** [K4ryuu/K4-RPG#7]
Hi, i tested 4 skills at my server and only Health works.. health regenerarion, vampire and thorns don't work.. said skills upgraded, but nothing happened..i write about bug in discord too but i ask to write a issue about bug to ghithub..

**Comment by K4ryuu** [comment]
Some skills work only with Linux as its shows in the list.

I develop for Linux only and will be developing for Linux only. If it supports Windows magically its not on purpose.

**Comment by omega6428** [comment]
hi, i tested only skills that NOT write "linux only".. Health regeneration
and Vampire also not working that NOT specified.. please specify if other
skills not working else Backstab, shoot damage multiplier and knife damage
multiplier that only specified "linux only" i need only life/armor
regeneration and vampire/thorns that no ONE works:(.

**Comment by Oz-Lin** [comment]
Jumping in to repost the error log.
Also it looks like the upgraded skills are gone when changing to another map,  (need to level up the skills from level 1 again)
Player exps and skill points are still there correctly in `k4-rpg_players` database table. 
But in the `k4-rpg_playerskills` database table, you can see the duplicated entries for skills (same steamid64, but duplicated skill and level).
![图片](https://github.com/user-attachments/assets/c9c29687-9be9-493d-ba61-7b6080fa1afe)


13:02:30 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: 76561198016810091
   at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at K4RPGSkillHealthRegen.PluginK4RPGSkillHealthRegen.<OnAllPluginsLoaded>b18_2(CCSPlayerController player, Int32 level)
   at K4RPG.Plugin.<>cDisplayClass32_1.<Initialize_Events>b__5(KeyValuePair2 x)
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at K4RPG.Plugin.<Initialize_Events>b32_1(EventPlayerSpawn event, GameEventInfo info)
   at InvokeStub_GameEventHandler1.Invoke(Object, Span1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by omega6428** [comment]
compiled with v.259.. same error:
11:23:06 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: 76561198016810091
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at K4RPGSkillHealthRegen.PluginK4RPGSkillHealthRegen.<OnAllPluginsLoaded>b__18_2(CCSPlayerController player, Int32 level)
   at K4RPG.Plugin.<>c__DisplayClass32_1.<Initialize_Events>b__5(KeyValuePair`2 x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at K4RPG.Plugin.<Initialize_Events>b__32_1(EventPlayerSpawn event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

mean CSSharp is buuged.. need to wait 2-3 years for SOURCE MOD v2.0

**Comment by Oz-Lin** [comment]
Looks like there's a bug with handling databases

**Comment by omega6428** [comment]
i use standard mysql database... please tell me if exist a dedicated light database for CS source2 plugins that can use mysql structure

**Comment by K4ryuu** [comment]
I'm deploying now K4-System's rework this weekend and after that I check on RPG aswell ❤️ 
Sadly this other rework consumed lot of time

**Comment by kokobeanies** [comment]
Any data base update on this? Im having same issue as OZ-lin
